keys:
  - &douse-nixos age12mh3wrwj3j3kcv2gftqj8azh36ayfya02qwdzlkgc4pu2zazj3sqy3aacr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *douse-nixos
 
